#!/bin/bash

# SCRIPT DEVELOPED BY BIDURADHIKARI (biduradhikari@gmail.com)

# ICON=/PATH-TO-ICON-FILE								   # UNCOMMENT IF YOU HAVE AN ICON FILE (.icns file in mac)

MountDirectory=~/.rclone_mount_directory  # change as needed

ping -c 1 -q google.com >&/dev/null       #CHECKING IF WE HAVE NETWORK
if [ $? -eq 0 ]; then
    :
else
  zenity --warning -text "Please check network connection." &
  exit 0
fi

array=()																   # to store remote names for display in dialog

while read -r line
do
	CHECKMPOINT="$MountDirectory/$line"
  if [[ $(mount | awk -v CHECK="$CHECKMPOINT" '$3 == CHECK {print $3}') = "" ]]; then   #remote is not mounted
    array+=$line                                # only remotes not already mounted are added to array
    array+=" "                                  # if spaces not added between names, the dialog will throw a single selection
  fi
done <<< "$(/usr/local/bin/rclone listremotes)"

if (( ${#array[@]} == 0 )); then								# all of the remotes mounted, array empty
		zenity --warning -text 'No drives left to mount!' & exit 0
else
		output=$(zenity --list -multiple  -ok-label Mount $array)
		set -f; IFS=\|
		for item in $output; do
			MPOINT="$MountDirectory/$item"
			mkdir -p $MPOINT
			if [ -z "${ICON}" ]; then
				/usr/local/bin/rclone mount $item $MPOINT --vfs-cache-mode writes > /dev/null 2>&1 &
			else
				/usr/local/bin/rclone mount $item $MPOINT --vfs-cache-mode writes -ovolicon=$ICON > /dev/null 2>&1 &
			fi
		done
		set =f; unset IFS
fi
exit 0
